trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.301'

- task: CmdLine@2
  displayName: "Microsoft.Playwright.CLI"
  inputs:
    script: 'dotnet tool install --global Microsoft.Playwright.CLI'

- task: CmdLine@2
  inputs:
    script: 'playwright install'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: settings .runsettings
