trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

schedules:
- cron: "0 0,6,12,18 * * 1-5"
  displayName: Run each 6 horus
  always: true
  branches:
    include:
    - master
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.301'
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  displayName: 'Install PlayWright CLI'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global Microsoft.Playwright.CLI'

- task: CmdLine@2
  displayName: 'Install PlayWright'
  inputs:
    script: 'playwright install'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    arguments: /p:settings=sauceDemo/.runsettings
